- name: Play variables
  hosts: localhost
  vars:
    message: "Hello, Ansible Play variable!"
  tasks:
    - name: Print a message
      debug:
        msg: "{{ message }}"


# In ansible, variables can be defined at different levels, playbook level, task level, role level, or inventory level. 
# This example, we define variable called `message` at playbook level and used in task to print message using the `debug` module. 
# if value is not defined at playbook level, ansible will look for the variable in role level and then inventory level.
# if value is variable or starts with `{{` and ends with `}}`, ansible will treat it as a variable and will look 
# for the value of the variable in the defined levels.
# key: "message" is the variable name and value is "Hello, Ansible!" which is a string.
# key: "msg" is the parameter of the debug module which is used to print the message.
# key: "{{ value }}" is the syntax to access the value of the variable defined at playbook level.
# key: "{{ value }} some other string" access the value of the variable at playbook level and concatenate it with some other string.
# key: "{{ value | default('default value') }}" access the value of the variable at playbook level and if it is not defined, it will use the default value.
# key: "{{ value | default('default value') | upper }}" access the value of the variable at playbook level and if it is not defined, it will use the default value and convert it to upper case.
# key: some other string {{ value }} access the value of the variable at playbook level and concatenate it with some other string.


- name: Task variables
  hosts: localhost
  tasks:
    - name: Print a message
      debug:
        msg: "{{ message }}"
      vars:
        message: "Hello, Ansible Task variable!"

# This variable is defined at the task level and is only available within this task.

- name: Role variables
  hosts: localhost
  roles:
    - demo
# This variable is defined at the role level and is only available within this role.    

# ansible-playbook 03-vars.yml -e message="cli variable" 
# this will override the variable defined at playbook level and task level.
# from command line, we can pass variables using -e or --extra-vars option.
# if same variable is defined at multiple levels, ansible will use the value defined at the highest level.
# precedence order of variable definition is: command line > playbook > role > task > inventory.


# Variables are three types in ansible, 1. static variables, 2. dynamic variables, 3. facts.
# static variables are defined in playbook, role, task or inventory and their values are fixed. example: message: "Hello, Ansible!"
# dynamic variables are defined using jinja2 expressions and their values are calculated at runtime. example: message: "{{ ansible_hostname }}"     
# facts are variables that are automatically discovered by ansible and their values are collected from the managed nodes. example: ansible_hostname, ansible_os_family, ansible_distribution, ansible_distribution_version, ansible_default_ipv4.address, etc.  

# Also, there is Normal, list, and Map variables. 
# Normal variables are defined using key-value pairs, list variables are defined using a list of values, and map variables are defined using a dictionary of key-value pairs.
# Example of normal variable: message: "Hello, Ansible!"
# Example of list variable: messages: ["Hello, Ansible!", "Hello, Ansible!"]  
# Example of map variable: messages: { message1: "Hello, Ansible!", message2: "Hello, Ansible!" }

# Variables have data types, string, integer, float, boolean, list, and dictionary.
# Example of string variable: message: "Hello, Ansible!"
# Example of integer variable: number: 10
# Example of float variable: number: 10.5 
# Example of boolean variable: flag: true
# Example of list variable: messages: ["Hello, Ansible!", "Hello, Ansible!"]
# Example of dictionary variable: messages: { message1: "Hello, Ansible!", message2: "Hello, Ansible!" }
# Example of variable with jinja2 expression: message: "{{ ansible_hostname }}"
# Example of variable with jinja2 expression and filter: message: "{{ ansible_hostname | upper }}"